### ISSUE TITLE
Fail fast upload request if running out of disk space

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/motion#179]
Motion should return error to upload request if it is running out of disk space.
- Remaining disk space can be checked using cross platform pkg. https://github.com/shirou/gopsutil/
- Blob length can be checked using content-length request header. Explore below edge cases
  - How does this work with multi-part upload
  - How does transport compression impact this value
  - What if this header is missing

**Comment by gammazero** [comment]
There is also this cross-platform disk usage package. It may have a bit less baggage:
https://github.com/ipni/storetheindex/tree/main/fsutil/disk
Reference: https://pkg.go.dev/github.com/ipni/storetheindex/fsutil/disk

> How does this work with multi-part upload

If we configure a maximum size per part, then we can check if there is enough remaining space to store the part. Otherwise, we just configure a usage limit beyond which we do not allow any more uploads. That limit is checked before each upload, and periodically during upload.

>  How does transport compression impact this value

Probably need to configure a usage limit that allows enough space to account for compression.

>  What if this header is missing

We can either require the header, or periodically check our limit during upload.
